### PR TITLE
Add Jumphost

### PR DESCRIPTION
**Pull request by briankfitzwater**
- Creates Jumphost AMI from hardened Ubuntu AMI
- Creates auto-scaling group and launch configuration to spawn a Jumphost in both public subnets of the mgmt account based on the [Linux Bastion Host on AWS Reference Architecture](https://aws.amazon.com/quickstart/architecture/linux-bastion/)

### CODE REVIEW

**Comment by briankfitzwater** [comment]
Need to find a better docker image for CircleCI

**Comment by Vermyndax** [comment]
Did you try 18F's alpine image? That's what I'm using on the pipeline to build hardened AMIs.

**Comment by briankfitzwater** [comment]
I thought about that, but I'm not sure we want to be dependant on the 18F infrastructure.  And then I got kind of bullheaded about getting packer to work.

**Comment by briankfitzwater** [comment]
[DEV - Implement SSH jump host in grace-example](https://trello.com/c/kMDUHOb4/671-dev-implement-ssh-jump-host-in-grace-example)

**Comment by briankfitzwater** [comment]
[DEV - Implement hardened baseline images in grace-example](https://trello.com/c/3PxcGnA4/670-dev-implement-hardened-baseline-images-in-grace-example)

**Review by Vermyndax — APPROVED** [review]

**Pull request merged**
